apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: example/testnf-du-large
  labels:
    name: testnf-du-large
  name: testnf-du-large
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|example|testnf-du-large'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testnf-du-large
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: sriov-pass
      labels:
        name: testnf-du-large
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: vmwaresaas.jfrog.io/registry/testnf-du-flexran-base:2.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: testnf-du-large
        ports:
        - containerPort: 5201
          name: tcp
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            hugepages-1Gi: 16Gi
            intel.com/sriovigbuio: "2"
            intel.com/sriovpass: "1"
            intel.com/sriovvfio: "1"
            memory: 32Gi
          requests:
            cpu: "12"
            hugepages-1Gi: 16Gi
            intel.com/sriovigbuio: "2"
            intel.com/sriovpass: "1"
            intel.com/sriovvfio: "1"
            memory: 32Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/huge
          name: huge
        - mountPath: /sys
          name: sys
        - mountPath: /dev
          name: dev
        - mountPath: /host/proc
          name: proc
      nodeSelector:
        role: high-perf
      restartPolicy: Always
      serviceAccount: testnf-du-large
      serviceAccountName: testnf-du-large
      volumes:
      - emptyDir:
          medium: HugePages
        name: huge
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /proc
          type: ""
        name: proc
