apiVersion: v1
kind: Service
metadata: # kpt-merge: /testnf-du-large
  name: testnf-du-large
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|testnf-du-large'
spec:
  type: ClusterIP
  ports:
  - port: 5201
    targetPort: tcp
    protocol: TCP
    name: tcp
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    name: testnf-du-large
